<Project>
  <Import Project="eng\MyCO.Version.props" />
  <PropertyGroup>
    <Authors>MyCO Contributors</Authors>
    <Company>MyCO Contributors</Company>
    <Product>MyCO</Product>
    <Title>MyCO</Title>
    <Description>MyCO</Description>
    <Copyright>Copyright © 2026 MyCO Contributors</Copyright>
    <RepositoryType>git</RepositoryType>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>
</Project>
