using System.Reflection;

namespace MyCodex;

// Reads release and protocol metadata generated by the shared MSBuild props file.
public static class BuildInfo
{
    private static readonly IReadOnlyDictionary<string, string> Metadata =
        typeof(BuildInfo).Assembly
            .GetCustomAttributes<AssemblyMetadataAttribute>()
            .ToDictionary(
                attribute => attribute.Key,
                attribute => attribute.Value ?? string.Empty,
                StringComparer.Ordinal);

    public static string Version { get; } =
        (typeof(BuildInfo).Assembly
             .GetCustomAttribute<AssemblyInformationalVersionAttribute>()
             ?.InformationalVersion ?? "0.0.0")
        .Split('+', 2)[0];

    public static int ProtocolVersion { get; } = ReadInt("MyCodexProtocolVersion");
    public static int ConfigSchemaVersion { get; } = ReadInt("MyCodexConfigSchemaVersion");
    public static int CalibrationSchemaVersion { get; } =
        ReadInt("MyCodexCalibrationSchemaVersion");

    private static int ReadInt(string key)
    {
        return Metadata.TryGetValue(key, out var value) &&
               int.TryParse(value, out var parsed)
            ? parsed
            : throw new InvalidOperationException($"Required build metadata '{key}' is missing.");
    }
}
